networks:
   database-movies-network:
       name: database-movies-network
   database-express-network:
       name: database-express-network
   redis-network:
       name: redis-network
   database-seed-network:
       name: database-seed-network    

volumes:
  dbdata:

services:

  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - '9000:9000'
    environment:
        - MONGODB_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@database:27017
        - REDIS_URI=redis://redis
        - ENABLE_WRITING_HANDLERS=false
    networks:
       - database-movies-network
       - redis-network
    depends_on:
      - database
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - redis-network # Temp fix to specify network, will change later for network isolation

  database:
    container_name: mongodb
    image: mongo:8.0-rc
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    networks:
      - database-movies-network
      - database-express-network
      - database-seed-network
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db

  mongodb-seed:
    container_name: mongodb-seed
    image: mongo:8.0-rc
    depends_on:
      - database
    networks:
      - database-seed-network
    volumes:
      - type: bind
        source: ./seeding.json
        target: /seeding.json
    command:
      mongoimport --authenticationDatabase=admin --db tmdb_movies --collection movies --drop --jsonArray --file /seeding.json mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@database:27017
      
        

  mongo-express:
    container_name: express
    image: mongo-express:1.0-20-alpine3.19
    restart: always # fixes MongoNetworkError caused by mongodb not being ready when mongo-express starts.
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@database:27017/
    networks:
       - database-express-network
    depends_on:
      - database     